### ISSUE TITLE
Do you want me to able this @theoyeah ?

### ISSUE THREAD

**Issue by Wither362** [Theoyeah/Theoyeah-Fnf-Engine#27]
https://github.com/Theoyeah/Theoyeah-Fnf-Engine/blob/f76a2dfc8dc889a547e73c849864a29f01c8c66f/source/options/GameplaySettingsSubState.hx#L101

it’s the multiplicativeValue, do I activate it?

**Comment by Theoyeah** [comment]
If you want

**Comment by Wither362** [comment]
Ok
